Player can do /player <playername> attack interval <ticks> on themselves
MultiCoreNetwork/carpet-redcraft-addons pull request #20
Opened 2021-02-16 17:03 UTC by DukeEdivad05

2021-02-16 18:45 UTC, BisUmTo commented
Gli script non vengono caricati automaticamente. 

Per ogni script va:
- creata una regola in [CarpetRedCraftSettings](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/blob/master/src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java)
- registrato lo script in [CarpetRedCraftExtension](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/blob/master/src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java )
- aggiunta la documentazione in [README](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/blob/master/README.md) e in [README_IT](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/blob/master/README_IT.md)

2021-02-17 18:30 UTC, BisUmTo requested changes

2021-02-17 18:30 UTC, BisUmTo commented on README.md
> +- [playerme](#playerme)
Da posizionare nel punto corretto, al fine che le regole siano disposte in ordine alfabetico

2021-02-17 18:30 UTC, BisUmTo commented on README.md
> +- Categories: `SURVIVAL`, `FEATURE`, `REDCRAFT`, `COMMAND`
Da posizionare nel punto corretto, al fine che le regole siano disposte in ordine alfabetico

2021-02-17 18:30 UTC, BisUmTo commented on README_IT.md
> +- [playerme](#playerme)
Da posizionare nel punto corretto, al fine che le regole siano disposte in ordine alfabetico

2021-02-17 18:30 UTC, BisUmTo commented on README_IT.md
> +- Categories: `SURVIVAL`, `FEATURE`, `REDCRAFT`, `COMMAND`
Da posizionare nel punto corretto, al fine che le regole siano disposte in ordine alfabetico

2021-02-17 18:30 UTC, BisUmTo commented on src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
> +        CarpetScriptServer.registerSettingsApp(redcraftDefaultScript("playerme", false));
Da posizionare nel punto corretto, al fine che le regole siano disposte in ordine alfabetico

2021-02-17 18:30 UTC, BisUmTo commented on src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
> +    public static boolean deoppedPlayerme = true;
da rinominare in commandPlayerme per consistenza

2021-02-17 18:30 UTC, BisUmTo commented on README.md
> +- Categories: `SURVIVAL`, `FEATURE`, `REDCRAFT`, `COMMAND`
da rinominare in commandPlayerme per consistenza

2021-02-17 18:30 UTC, BisUmTo commented on README.md
> +- [playerme](#playerme)
da rinominare in commandPlayerme per consistenza

2021-02-17 18:30 UTC, BisUmTo commented on README_IT.md
> +- [playerme](#playerme)
da rinominare in commandPlayerme per consistenza

2021-02-17 18:30 UTC, BisUmTo commented on README_IT.md
> +- Categories: `SURVIVAL`, `FEATURE`, `REDCRAFT`, `COMMAND`
da rinominare in commandPlayerme per consistenza

2021-02-17 18:30 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/playerme.sc
> +        run('player '+name+' jump continuous')),
funziona su player online?

2021-02-17 18:30 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/playerme.sc
> +        'hotbarslot' -> {'type' -> 'int', 'min' -> 1, 'max' -> 9, 'suggest' -> [1,2,3,4,5,6,7,8,9]},
Da 1 a 9 oppure da 0 a 8?

2021-02-17 19:06 UTC, DukeEdivad05 commented on src/main/resources/assets/carpet-redcraft-addons/scripts/playerme.sc
> +        'hotbarslot' -> {'type' -> 'int', 'min' -> 1, 'max' -> 9, 'suggest' -> [1,2,3,4,5,6,7,8,9]},
da 1 a 9 come nei consigliati

2021-02-21 17:22 UTC, BisUmTo approved these changes

2021-03-02 13:53 UTC, merged