fastRedstoneCrafting
MultiCoreNetwork/carpet-redcraft-addons pull request #24
Opened 2021-02-22 13:35 UTC by DukeEdivad05

Resolves #15

2021-02-27 17:34 UTC, BisUmTo requested changes

2021-02-27 17:34 UTC, BisUmTo commented on README.md
> +Aggiunge crafting alternativi di dispenser e repeater
Questo è il file inglese...

Adds fast redstone crafting for Dispenser and Repeater.

2021-02-27 17:39 UTC, BisUmTo commented
File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/recipes/dispenser`

Line 55: 
```json
[
   "has_item_2",
   "has_the_recipe"
]
```

2021-02-27 17:41 UTC, BisUmTo commented
File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/fast_redstone_crafting.json`

Line 5:
```json
"text": "Some fast redstone crafting by BisUmTo, Gnottero & DukeEdivad05"
```

2021-02-27 17:44 UTC, BisUmTo commented
File: carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/recipes/fast_redstone_crafting/dispenser/dispenser1.json

Line 21:
```json
   "item": "minecraft:dispenser"
}
```

Mal-formattazione del JSON, basta mettere a capo la parentesi graffa.

2021-02-27 17:45 UTC, BisUmTo commented
File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/recipes/fast_redstone_crafting/dispenser/dispenser2.json`

Line 13:
```json
   "item": "minecraft:dispenser"
}
```

Mal-formattazione del JSON, basta mettere a capo la parentesi graffa.

2021-02-27 17:50 UTC, BisUmTo commented
File: carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/functions/fast_redstone_crafting/uninstall.json

Line 10:
```json
datapack disable "file/RedPack - Fast Redstone Crafting"
```

Il datapack disabilitato deve coincidere con il nome del file

2021-02-27 19:30 UTC, DukeEdivad05 commented
> File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/fast_redstone_crafting.json`
> 
> Line 5:
> ```json
> "text": "Some fast redstone crafting by BisUmTo, Gnottero & DukeEdivad05"
> ```
> 
> Mancano i tuoi crediti

Sei sicuro servano??

2021-02-28 09:46 UTC, DukeEdivad05 commented
> File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/recipes/dispenser/dispenser1.json`
> 
> Line 55:
> 
> ```json
> [
>    "has_item_2",
>    "has_the_recipe"
> ]
> ```
> 
> Manca un criterio

Esiste un crafting delle stringhe??

2021-02-28 16:51 UTC, BisUmTo commented
> > File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/fast_redstone_crafting.json`
> > Line 5:
> > ```json
> > "text": "Some fast redstone crafting by BisUmTo, Gnottero & DukeEdivad05"
> > ```
> > 
> > 
> > Mancano i tuoi crediti
> 
> Sei sicuro servano??

Beh, sì...

2021-02-28 16:51 UTC, BisUmTo commented
> > File: `carpet-redcraft-addons/src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip/data/redpack/advancements/fast_redstone_crafting/recipes/dispenser/dispenser1.json`
> > Line 55:
> > ```json
> > [
> >    "has_item_2",
> >    "has_the_recipe"
> > ]
> > ```
> > 
> > 
> > Manca un criterio
> 
> Esiste un crafting delle stringhe??

`has_the_recipe` si riferisce al controllo sul dispenser stesso e non sull'ingrediente

2021-02-28 17:03 UTC, BisUmTo approved these changes

2021-03-02 13:53 UTC, merged