Added moss.sc
MultiCoreNetwork/carpet-redcraft-addons pull request #43
Opened 2021-03-25 11:52 UTC by DukeEdivad05

resolves #32

2021-03-25 23:09 UTC, BisUmTo requested changes

2021-03-25 23:09 UTC, BisUmTo commented on src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
> +            desc="bonemealing a mossy block will became a moss_block.",
`desc="Allow to obtain moss by bonemealing mossy blocks.",`

Cerchiamo di mantenere la stessa descrizione nella documentazione e nel gioco.

2021-03-25 23:09 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +inventory_remove(player()~'command_name', 'bone_meal');
Geniale! Non sapevo si potesse fare così semplicemente!

Cioè, pensavo lo togliesse da un punto a caso dell'inventario, non dalla mano!

2021-03-25 23:09 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +inventory_remove(player()~'command_name', 'bone_meal');
`inventory_remove(player, 'bone_meal');`

2021-03-25 23:09 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +inventory_remove(player()~'command_name', 'bone_meal');
Indentare il codice se possibile:

Quando viene aperta una parentesi tonda e non è ancora chiusa, le linee successive vengono tabulate.

```
ciao (
    questo
    è (
        un 
        esempio
    )
    di ()
    indentatura
)
```

2021-03-25 23:10 UTC, BisUmTo commented
Ammetto di essere un po' scettico sul nome... lo trovo molto generico, ma siccome è una cosa temporanea - si spera - penso vada bene...

2021-03-26 07:05 UTC, DukeEdivad05 commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +inventory_remove(player()~'command_name', 'bone_meal');
> Geniale! Non sapevo si potesse fare così semplicemente!
> 
> Cioè, pensavo lo togliesse da un punto a caso dell'inventario, non dalla mano!

Ora che mi ci fai pensare potrebbe essere che lo rimuove a caso dall'inventario... poi controllo meglio

2021-03-26 07:14 UTC, BisUmTo approved these changes

2021-03-26 07:14 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +    return
Non necessaria, lo fa in automatico

2021-03-26 12:33 UTC, DukeEdivad05 commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +    return
Cosa non necessario??

2021-03-26 12:35 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +    return
Return

2021-03-27 12:25 UTC, BisUmTo requested changes

2021-03-27 12:25 UTC, BisUmTo commented on src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
> +        inventory_set(player, if(hand=='mainhand',player~'selected_slot',-1), count - 1, item);
Cala gli oggetti anche in creative

2021-03-27 19:56 UTC, BisUmTo approved these changes

2021-03-27 19:56 UTC, merged